version 0.3

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -523,9 +523,71 @@ fi
 
 
 
+if test /usr/local != "$exec_prefix" -a /usr/local != "$prefix" ; then
+  CPPFLAGS="$CPPFLAGS -I/usr/local/include"
+  LDFLAGS="$LDFLAGS -L/usr/local/lib"
+fi
 
-	PKG_CPPFLAGS="${PKG_CPPFLAGS} -I/usr/local/include/ "
-	PKG_LIBS="${PKG_LIBS} -L/usr/local/lib/ -lgmp"
+
+echo $ac_n "checking for __gmpz_ui_sub in -lgmp""... $ac_c" 1>&6
+echo "configure:534: checking for __gmpz_ui_sub in -lgmp" >&5
+ac_lib_var=`echo gmp'_'__gmpz_ui_sub | sed 'y%./+-%__p_%'`
+if eval "test \"`echo '$''{'ac_cv_lib_$ac_lib_var'+set}'`\" = set"; then
+  echo $ac_n "(cached) $ac_c" 1>&6
+else
+  ac_save_LIBS="$LIBS"
+LIBS="-lgmp  $LIBS"
+cat > conftest.$ac_ext <<EOF
+#line 542 "configure"
+#include "confdefs.h"
+/* Override any gcc2 internal prototype to avoid an error.  */
+/* We use char because int might match the return type of a gcc2
+    builtin and then its argument prototype would still apply.  */
+char __gmpz_ui_sub();
+
+int main() {
+__gmpz_ui_sub()
+; return 0; }
+EOF
+if { (eval echo configure:553: \"$ac_link\") 1>&5; (eval $ac_link) 2>&5; } && test -s conftest${ac_exeext}; then
+  rm -rf conftest*
+  eval "ac_cv_lib_$ac_lib_var=yes"
+else
+  echo "configure: failed program was:" >&5
+  cat conftest.$ac_ext >&5
+  rm -rf conftest*
+  eval "ac_cv_lib_$ac_lib_var=no"
+fi
+rm -f conftest*
+LIBS="$ac_save_LIBS"
+
+fi
+if eval "test \"`echo '$ac_cv_lib_'$ac_lib_var`\" = yes"; then
+  echo "$ac_t""yes" 1>&6
+    ac_tr_lib=HAVE_LIB`echo gmp | sed -e 's/[^a-zA-Z0-9_]/_/g' \
+    -e 'y/abcdefghijklmnopqrstuvwxyz/ABCDEFGHIJKLMNOPQRSTUVWXYZ/'`
+  cat >> confdefs.h <<EOF
+#define $ac_tr_lib 1
+EOF
+
+  LIBS="-lgmp $LIBS"
+
+else
+  echo "$ac_t""no" 1>&6
+{ echo "configure: error: GNU MP not found, or not 4.1.4 or up, see http://swox.com.gmp" 1>&2; exit 1; }
+fi
+
+
+
+
+#PKG_CPPFLAGS="${PKG_CPPFLAGS} -I/usr/local/include/ "
+#PKG_LIBS="${PKG_LIBS} -L/usr/local/lib/ -lgmp"
+
+PKG_CPPFLAGS="${PKG_CPPFLAGS} -I/usr/local/include/ "
+PKG_LIBS="${PKG_LIBS} -L/usr/local/lib/ -lgmp"
+
+
+ 
 
 
 
